detect ipopt's ampl interface

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -478,8 +478,8 @@ ac_subdirs_all="$ac_subdirs_all ThirdParty/Lapack"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/HSL"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/ASL"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/FilterSQP"
-ac_subdirs_all="$ac_subdirs_all ThirdParty/Mumps"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Metis"
+ac_subdirs_all="$ac_subdirs_all ThirdParty/Mumps"
 ac_subdirs_all="$ac_subdirs_all CoinUtils"
 ac_subdirs_all="$ac_subdirs_all Osi"
 ac_subdirs_all="$ac_subdirs_all Clp"
@@ -1164,12 +1164,12 @@ Optional Packages:
   --with-filtersqp-datadir
                           directory with data files for using project
                           FilterSQP
-  --with-mumps-lib linker flags for using project Mumps
-  --with-mumps-incdir directory with header files for using project Mumps
-  --with-mumps-datadir directory with data files for using project Mumps
   --with-metis-lib linker flags for using project Metis
   --with-metis-incdir directory with header files for using project Metis
   --with-metis-datadir directory with data files for using project Metis
+  --with-mumps-lib linker flags for using project Mumps
+  --with-mumps-incdir directory with header files for using project Mumps
+  --with-mumps-datadir directory with data files for using project Mumps
   --with-coinutils-lib linker flags for using project CoinUtils
   --with-coinutils-incdir directory with header files for using project
                           CoinUtils
@@ -21702,127 +21702,6 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-echo "$as_me:$LINENO: checking whether project Mumps is available" >&5
-echo $ECHO_N "checking whether project Mumps is available... $ECHO_C" >&6
-
-coin_has_mumps=notGiven
-coin_have_project_dir=no
-
-# check if user wants to skip project in any case
-
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = "Mumps"; then
-      coin_has_mumps=skipping
-    fi
-    if test $dir = "ThirdParty/Mumps"; then
-      coin_has_mumps=skipping
-    fi
-  done
-fi
-
-if test $coin_has_mumps != skipping; then
-  if test $PACKAGE_TARNAME = mumps; then
-    coin_has_mumps=.
-    coin_have_project_dir=yes
-  fi
-
-
-# Check whether --with-m4_tolower(Mumps)-lib or --without-m4_tolower(Mumps)-lib was given.
-if test "${with_mumps_lib+set}" = set; then
-  withval="$with_mumps_lib"
-  coin_has_mumps=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Mumps)-incdir or --without-m4_tolower(Mumps)-incdir was given.
-if test "${with_mumps_incdir+set}" = set; then
-  withval="$with_mumps_incdir"
-  coin_has_mumps=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Mumps)-datadir or --without-m4_tolower(Mumps)-datadir was given.
-if test "${with_mumps_datadir+set}" = set; then
-  withval="$with_mumps_datadir"
-  coin_has_mumps=installed
-fi;
-
-
-
-
-
-fi
-
-# check if project is available in present directory
-if test "$coin_has_mumps" = notGiven; then
-  if test -d $srcdir/ThirdParty/Mumps; then
-    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
-    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
-    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
-    for i in $srcdir/ThirdParty/Mumps/MUMPS/src/dmumps_part1.F; do
-         if test -r $i; then
-           coin_have_project_dir=yes
-         fi
-       done
-
-    if test $coin_have_project_dir = yes; then
-      coin_has_mumps=ThirdParty/Mumps
-    fi
-  fi
-fi
-
-# check for project by using pkg-config, if pkg-config is available
-if test $coin_has_mumps = notGiven; then
-  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
-  if test -n "$PKG_CONFIG" ; then
-    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
-    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
-
-if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "coinmumps"; then
-    COINMUMPS_VERSION=`$PKG_CONFIG --modversion "coinmumps" 2>/dev/null`
-    coin_has_mumps="$COINMUMPS_VERSION"
-  else
-    COINMUMPS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "coinmumps"`
-
-  fi
-else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module coinmumps without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module coinmumps without pkg-config\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
-    export PKG_CONFIG_PATH
-  fi
-fi
-
-echo "$as_me:$LINENO: result: $coin_has_mumps" >&5
-echo "${ECHO_T}$coin_has_mumps" >&6
-
-echo "$as_me:$LINENO: checking whether project Mumps needs to be configured" >&5
-echo $ECHO_N "checking whether project Mumps needs to be configured... $ECHO_C" >&6
-if test "$coin_have_project_dir" = yes ; then
-
-  if test -r $srcdir/ThirdParty/Mumps/configure; then
-    coin_subdirs="$coin_subdirs ThirdParty/Mumps"
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-
-subdirs="$subdirs ThirdParty/Mumps"
-
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
 echo "$as_me:$LINENO: checking whether project Metis is available" >&5
 echo $ECHO_N "checking whether project Metis is available... $ECHO_C" >&6
 
@@ -21933,6 +21812,127 @@ echo "${ECHO_T}yes" >&6
 
 
 subdirs="$subdirs ThirdParty/Metis"
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+echo "$as_me:$LINENO: checking whether project Mumps is available" >&5
+echo $ECHO_N "checking whether project Mumps is available... $ECHO_C" >&6
+
+coin_has_mumps=notGiven
+coin_have_project_dir=no
+
+# check if user wants to skip project in any case
+
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Mumps"; then
+      coin_has_mumps=skipping
+    fi
+    if test $dir = "ThirdParty/Mumps"; then
+      coin_has_mumps=skipping
+    fi
+  done
+fi
+
+if test $coin_has_mumps != skipping; then
+  if test $PACKAGE_TARNAME = mumps; then
+    coin_has_mumps=.
+    coin_have_project_dir=yes
+  fi
+
+
+# Check whether --with-m4_tolower(Mumps)-lib or --without-m4_tolower(Mumps)-lib was given.
+if test "${with_mumps_lib+set}" = set; then
+  withval="$with_mumps_lib"
+  coin_has_mumps=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Mumps)-incdir or --without-m4_tolower(Mumps)-incdir was given.
+if test "${with_mumps_incdir+set}" = set; then
+  withval="$with_mumps_incdir"
+  coin_has_mumps=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Mumps)-datadir or --without-m4_tolower(Mumps)-datadir was given.
+if test "${with_mumps_datadir+set}" = set; then
+  withval="$with_mumps_datadir"
+  coin_has_mumps=installed
+fi;
+
+
+
+
+
+fi
+
+# check if project is available in present directory
+if test "$coin_has_mumps" = notGiven; then
+  if test -d $srcdir/ThirdParty/Mumps; then
+    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
+    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
+    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
+    for i in $srcdir/ThirdParty/Mumps/MUMPS/src/dmumps_part1.F; do
+         if test -r $i; then
+           coin_have_project_dir=yes
+         fi
+       done
+
+    if test $coin_have_project_dir = yes; then
+      coin_has_mumps=ThirdParty/Mumps
+    fi
+  fi
+fi
+
+# check for project by using pkg-config, if pkg-config is available
+if test $coin_has_mumps = notGiven; then
+  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
+  if test -n "$PKG_CONFIG" ; then
+    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
+    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
+
+if test -n "$PKG_CONFIG" ; then
+  if $PKG_CONFIG --exists "coinmumps"; then
+    COINMUMPS_VERSION=`$PKG_CONFIG --modversion "coinmumps" 2>/dev/null`
+    coin_has_mumps="$COINMUMPS_VERSION"
+  else
+    COINMUMPS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "coinmumps"`
+
+  fi
+else
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module coinmumps without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module coinmumps without pkg-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
+    export PKG_CONFIG_PATH
+  fi
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_mumps" >&5
+echo "${ECHO_T}$coin_has_mumps" >&6
+
+echo "$as_me:$LINENO: checking whether project Mumps needs to be configured" >&5
+echo $ECHO_N "checking whether project Mumps needs to be configured... $ECHO_C" >&6
+if test "$coin_have_project_dir" = yes ; then
+
+  if test -r $srcdir/ThirdParty/Mumps/configure; then
+    coin_subdirs="$coin_subdirs ThirdParty/Mumps"
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+subdirs="$subdirs ThirdParty/Mumps"
 
   else
     echo "$as_me:$LINENO: result: no" >&5
