added with-couenne-verbosity and with-couenne-checklevel flags for configure

diff --git a/Couenne/configure b/Couenne/configure
--- a/Couenne/configure
+++ b/Couenne/configure
@@ -1075,6 +1075,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-debug          compile all projects with debug options tests
+  --enable-debug-couenne compile this project (Couenne) with debug options
   --enable-doscompile     Under Cygwin, compile so that executables run under
                           DOS. Set to mingw to use gcc/g++/ld with
                           -mno-cygwin. Set to msvc to use cl/link. Default
@@ -1095,6 +1096,11 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-couenne-verbosity
+                          specify the debug verbosity level for project
+                          Couenne
+  --with-couenne-checklevel
+                          specify the sanity check level for project Couenne
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -1713,7 +1719,25 @@ else
   coin_debug_compile=false
 fi;
 
- # m4_ifvaln([],
+# Check whether --enable-debug-couenne or --disable-debug-couenne was given.
+if test "${enable_debug_couenne+set}" = set; then
+  enableval="$enable_debug_couenne"
+  case "${enableval}" in
+    yes) coin_debug_compile=true
+         enable_shared=no
+         ;;
+    no)  coin_debug_compile=false
+         ;;
+    *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-debug-couenne" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-debug-couenne" >&2;}
+   { (exit 1); exit 1; }; }
+         ;;
+ esac
+else
+  :
+fi;
+
+ # m4_ifvaln([Couenne],
 
 if test $coin_debug_compile = true; then
   echo "$as_me:$LINENO: result: yes" >&5
@@ -1723,7 +1747,46 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
- # m4_ifvaln([],
+
+# Check whether --with-couenne-verbosity or --without-couenne-verbosity was given.
+if test "${with_couenne_verbosity+set}" = set; then
+  withval="$with_couenne_verbosity"
+  if test "$withval" = yes; then
+                withval=1
+              fi
+              coin_couenne_verbosity=$withval
+else
+  coin_couenne_verbosity=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_COUENNE_VERBOSITY $coin_couenne_verbosity
+_ACEOF
+
+
+
+# Check whether --with-couenne-checklevel or --without-couenne-checklevel was given.
+if test "${with_couenne_checklevel+set}" = set; then
+  withval="$with_couenne_checklevel"
+  if test "$withval" = yes; then
+                withval=1
+              fi
+              coin_couenne_checklevel=$withval
+else
+  coin_couenne_checklevel=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_COUENNE_CHECKLEVEL $coin_couenne_checklevel
+_ACEOF
+
+
+# We use the following variable to have a string with the upper case
+# version of the project name
+COIN_PRJCT=COUENNE
+
+
+ # m4_ifvaln([Couenne],
 
 
 
@@ -6554,7 +6617,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6557 "configure"' > conftest.$ac_ext
+  echo '#line 6620 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7688,7 +7751,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:7691:" \
+echo "$as_me:7754:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8755,11 +8818,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8758: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8821: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8762: \$? = $ac_status" >&5
+   echo "$as_me:8825: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9023,11 +9086,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9026: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9089: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9030: \$? = $ac_status" >&5
+   echo "$as_me:9093: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9127,11 +9190,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9130: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9193: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9134: \$? = $ac_status" >&5
+   echo "$as_me:9197: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11472,7 +11535,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11475 "configure"
+#line 11538 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11572,7 +11635,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11575 "configure"
+#line 11638 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13916,11 +13979,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13919: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13982: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13923: \$? = $ac_status" >&5
+   echo "$as_me:13986: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14020,11 +14083,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14023: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14086: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14027: \$? = $ac_status" >&5
+   echo "$as_me:14090: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15590,11 +15653,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15593: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15656: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15597: \$? = $ac_status" >&5
+   echo "$as_me:15660: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15694,11 +15757,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15697: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15760: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15701: \$? = $ac_status" >&5
+   echo "$as_me:15764: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17901,11 +17964,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17904: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17967: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17908: \$? = $ac_status" >&5
+   echo "$as_me:17971: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18169,11 +18232,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18172: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18235: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18176: \$? = $ac_status" >&5
+   echo "$as_me:18239: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18273,11 +18336,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18276: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18339: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18280: \$? = $ac_status" >&5
+   echo "$as_me:18343: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
